[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = "1.68.0"
aws-types = "1.3.3"
image = "0.25.5"
tokio = { version = "1.38.1", features = ["full"] }
tokio-macros = { version = "0.2.0-alpha.6" }
